export type Imac = {
  "Introduction Date": string;
  "Discontinued Date": string;
  Processors: string;
  Architecture: string;
  "Geekbench 2 (32)": string;
  "Geekbench 2 (64)": string;
  "Geekbench 3 (32)": string;
  "Geekbench 3 (64)": string;
  "Geekbench 4 (SC)": string;
  "Geekbench 4 (MC)": string;
  "Processor Speed": string;
  "Processor Type": string;
  "Turbo Boost": string;
  "Custom Speeds": string;
  "Processor Upgrade": string;
  FPU: string;
  "System Bus Speed": string;
  "Cache Bus Speed": string;
  "ROM/Firmware Type": string;
  "EFI Architecture": string;
  "L1 Cache": string;
  "L2/L3 Cache": string;
  "RAM Type": string;
  "Min. RAM Speed": string;
  "Standard RAM": string;
  "Maximum RAM": string;
  "Motherboard RAM": string;
  "RAM Slots": string;
  "Video Card": string;
  "VRAM Type": string;
  "Standard VRAM": string;
  "Maximum VRAM": string;
  "Built-in Display": string;
  "Native Resolution": string;
  "2nd Display Support": string;
  "2nd Max. Resolution": string;
  "Standard Storage": string;
  "Std. Storage Speed": string;
  "Storage Dimensions": string;
  "Storage Interface": string;
  "Standard Optical": string;
  "Standard Disk": string;
  "Standard Modem": string;
  "Standard Ethernet": string;
  "Standard AirPort": string;
  "Standard Bluetooth": string;
  "USB Ports:string": string;
  "Firewire Ports": string;
  "Expansion Slots": string;
  "Expansion Bays": string;
  "Incl. Keyboard": string;
  "Incl. Input": string;
  "Case Type": string;
  "Form Factor": string;
  "Apple Order No": string;
  "Apple Subfamily": string;
  "Apple Model No": string;
  "Model ID": string;
  "Battery Type": string;
  "Battery Life": string;
  "Pre-Installed MacOS": string;
  "Maximum MacOS": string;
  "Minimum Windows": string;
  "Maximum Windows": string;
  "MacOS 9 Support": string;
  "Windows Support": string;
  Dimensions: string;
  "Avg. Weight": string;
  "Original Price (US)": string;
  "Est. Current Retail": string;
};
